/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConnectRouteImport } from './routes/connect'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as PairingRouteImport } from './routes/pairing'
import { Route as QuestionsRouteImport } from './routes/questions'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as UpdatesRouteImport } from './routes/updates'
import { Route as AnswerQuestionIdRouteImport } from './routes/answer.$questionId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectRoute = ConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const PairingRoute = PairingRouteImport.update({
  id: '/pairing',
  path: '/pairing',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestionsRoute = QuestionsRouteImport.update({
  id: '/questions',
  path: '/questions',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const UpdatesRoute = UpdatesRouteImport.update({
  id: '/updates',
  path: '/updates',
  getParentRoute: () => rootRouteImport,
} as any)
const AnswerQuestionIdRoute = AnswerQuestionIdRouteImport.update({
  id: '/answer/$questionId',
  path: '/answer/$questionId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/connect': typeof ConnectRoute
  '/notifications': typeof NotificationsRoute
  '/pairing': typeof PairingRoute
  '/questions': typeof QuestionsRoute
  '/settings': typeof SettingsRoute
  '/updates': typeof UpdatesRoute
  '/answer/$questionId': typeof AnswerQuestionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/connect': typeof ConnectRoute
  '/notifications': typeof NotificationsRoute
  '/pairing': typeof PairingRoute
  '/questions': typeof QuestionsRoute
  '/settings': typeof SettingsRoute
  '/updates': typeof UpdatesRoute
  '/answer/$questionId': typeof AnswerQuestionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/connect': typeof ConnectRoute
  '/notifications': typeof NotificationsRoute
  '/pairing': typeof PairingRoute
  '/questions': typeof QuestionsRoute
  '/settings': typeof SettingsRoute
  '/updates': typeof UpdatesRoute
  '/answer/$questionId': typeof AnswerQuestionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/connect'
    | '/notifications'
    | '/pairing'
    | '/questions'
    | '/settings'
    | '/updates'
    | '/answer/$questionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/connect'
    | '/notifications'
    | '/pairing'
    | '/questions'
    | '/settings'
    | '/updates'
    | '/answer/$questionId'
  id:
    | '__root__'
    | '/'
    | '/connect'
    | '/notifications'
    | '/pairing'
    | '/questions'
    | '/settings'
    | '/updates'
    | '/answer/$questionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConnectRoute: typeof ConnectRoute
  NotificationsRoute: typeof NotificationsRoute
  PairingRoute: typeof PairingRoute
  QuestionsRoute: typeof QuestionsRoute
  SettingsRoute: typeof SettingsRoute
  UpdatesRoute: typeof UpdatesRoute
  AnswerQuestionIdRoute: typeof AnswerQuestionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect': {
      id: '/connect'
      path: '/connect'
      fullPath: '/connect'
      preLoaderRoute: typeof ConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pairing': {
      id: '/pairing'
      path: '/pairing'
      fullPath: '/pairing'
      preLoaderRoute: typeof PairingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/questions': {
      id: '/questions'
      path: '/questions'
      fullPath: '/questions'
      preLoaderRoute: typeof QuestionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/updates': {
      id: '/updates'
      path: '/updates'
      fullPath: '/updates'
      preLoaderRoute: typeof UpdatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/answer/$questionId': {
      id: '/answer/$questionId'
      path: '/answer/$questionId'
      fullPath: '/answer/$questionId'
      preLoaderRoute: typeof AnswerQuestionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConnectRoute: ConnectRoute,
  NotificationsRoute: NotificationsRoute,
  PairingRoute: PairingRoute,
  QuestionsRoute: QuestionsRoute,
  SettingsRoute: SettingsRoute,
  UpdatesRoute: UpdatesRoute,
  AnswerQuestionIdRoute: AnswerQuestionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
