/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as ConnectRouteImport } from './routes/connect'
import { Route as LocationRouteImport } from './routes/location'
import { Route as MediaRouteImport } from './routes/media'
import { Route as NotesRouteImport } from './routes/notes'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as PairingRouteImport } from './routes/pairing'
import { Route as PlansRouteImport } from './routes/plans'
import { Route as QuestionsRouteImport } from './routes/questions'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as UpdatesRouteImport } from './routes/updates'
import { Route as AnswerQuestionIdRouteImport } from './routes/answer.$questionId'
import { Route as NotesIndexRouteImport } from './routes/notes.index'
import { Route as NotesNoteIdRouteImport } from './routes/notes.$noteId'
import { Route as PlansIndexRouteImport } from './routes/plans.index'
import { Route as PlansPlanIdRouteImport } from './routes/plans.$planId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectRoute = ConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationRoute = LocationRouteImport.update({
  id: '/location',
  path: '/location',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaRoute = MediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesRoute = NotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const PairingRoute = PairingRouteImport.update({
  id: '/pairing',
  path: '/pairing',
  getParentRoute: () => rootRouteImport,
} as any)
const PlansRoute = PlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestionsRoute = QuestionsRouteImport.update({
  id: '/questions',
  path: '/questions',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const UpdatesRoute = UpdatesRouteImport.update({
  id: '/updates',
  path: '/updates',
  getParentRoute: () => rootRouteImport,
} as any)
const AnswerQuestionIdRoute = AnswerQuestionIdRouteImport.update({
  id: '/answer/$questionId',
  path: '/answer/$questionId',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesIndexRoute = NotesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => NotesRoute,
} as any)
const NotesNoteIdRoute = NotesNoteIdRouteImport.update({
  id: '/$noteId',
  path: '/$noteId',
  getParentRoute: () => NotesRoute,
} as any)
const PlansIndexRoute = PlansIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PlansRoute,
} as any)
const PlansPlanIdRoute = PlansPlanIdRouteImport.update({
  id: '/$planId',
  path: '/$planId',
  getParentRoute: () => PlansRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/connect': typeof ConnectRoute
  '/location': typeof LocationRoute
  '/media': typeof MediaRoute
  '/notes': typeof NotesRouteWithChildren
  '/notifications': typeof NotificationsRoute
  '/pairing': typeof PairingRoute
  '/plans': typeof PlansRouteWithChildren
  '/questions': typeof QuestionsRoute
  '/settings': typeof SettingsRoute
  '/updates': typeof UpdatesRoute
  '/answer/$questionId': typeof AnswerQuestionIdRoute
  '/notes/$noteId': typeof NotesNoteIdRoute
  '/plans/$planId': typeof PlansPlanIdRoute
  '/notes/': typeof NotesIndexRoute
  '/plans/': typeof PlansIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/connect': typeof ConnectRoute
  '/location': typeof LocationRoute
  '/media': typeof MediaRoute
  '/notifications': typeof NotificationsRoute
  '/pairing': typeof PairingRoute
  '/questions': typeof QuestionsRoute
  '/settings': typeof SettingsRoute
  '/updates': typeof UpdatesRoute
  '/answer/$questionId': typeof AnswerQuestionIdRoute
  '/notes/$noteId': typeof NotesNoteIdRoute
  '/plans/$planId': typeof PlansPlanIdRoute
  '/notes': typeof NotesIndexRoute
  '/plans': typeof PlansIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/connect': typeof ConnectRoute
  '/location': typeof LocationRoute
  '/media': typeof MediaRoute
  '/notes': typeof NotesRouteWithChildren
  '/notifications': typeof NotificationsRoute
  '/pairing': typeof PairingRoute
  '/plans': typeof PlansRouteWithChildren
  '/questions': typeof QuestionsRoute
  '/settings': typeof SettingsRoute
  '/updates': typeof UpdatesRoute
  '/answer/$questionId': typeof AnswerQuestionIdRoute
  '/notes/$noteId': typeof NotesNoteIdRoute
  '/plans/$planId': typeof PlansPlanIdRoute
  '/notes/': typeof NotesIndexRoute
  '/plans/': typeof PlansIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calendar'
    | '/connect'
    | '/location'
    | '/media'
    | '/notes'
    | '/notifications'
    | '/pairing'
    | '/plans'
    | '/questions'
    | '/settings'
    | '/updates'
    | '/answer/$questionId'
    | '/notes/$noteId'
    | '/plans/$planId'
    | '/notes/'
    | '/plans/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calendar'
    | '/connect'
    | '/location'
    | '/media'
    | '/notifications'
    | '/pairing'
    | '/questions'
    | '/settings'
    | '/updates'
    | '/answer/$questionId'
    | '/notes/$noteId'
    | '/plans/$planId'
    | '/notes'
    | '/plans'
  id:
    | '__root__'
    | '/'
    | '/calendar'
    | '/connect'
    | '/location'
    | '/media'
    | '/notes'
    | '/notifications'
    | '/pairing'
    | '/plans'
    | '/questions'
    | '/settings'
    | '/updates'
    | '/answer/$questionId'
    | '/notes/$noteId'
    | '/plans/$planId'
    | '/notes/'
    | '/plans/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalendarRoute: typeof CalendarRoute
  ConnectRoute: typeof ConnectRoute
  LocationRoute: typeof LocationRoute
  MediaRoute: typeof MediaRoute
  NotesRoute: typeof NotesRouteWithChildren
  NotificationsRoute: typeof NotificationsRoute
  PairingRoute: typeof PairingRoute
  PlansRoute: typeof PlansRouteWithChildren
  QuestionsRoute: typeof QuestionsRoute
  SettingsRoute: typeof SettingsRoute
  UpdatesRoute: typeof UpdatesRoute
  AnswerQuestionIdRoute: typeof AnswerQuestionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect': {
      id: '/connect'
      path: '/connect'
      fullPath: '/connect'
      preLoaderRoute: typeof ConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/location': {
      id: '/location'
      path: '/location'
      fullPath: '/location'
      preLoaderRoute: typeof LocationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media': {
      id: '/media'
      path: '/media'
      fullPath: '/media'
      preLoaderRoute: typeof MediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes': {
      id: '/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof NotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pairing': {
      id: '/pairing'
      path: '/pairing'
      fullPath: '/pairing'
      preLoaderRoute: typeof PairingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plans': {
      id: '/plans'
      path: '/plans'
      fullPath: '/plans'
      preLoaderRoute: typeof PlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/questions': {
      id: '/questions'
      path: '/questions'
      fullPath: '/questions'
      preLoaderRoute: typeof QuestionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/updates': {
      id: '/updates'
      path: '/updates'
      fullPath: '/updates'
      preLoaderRoute: typeof UpdatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/answer/$questionId': {
      id: '/answer/$questionId'
      path: '/answer/$questionId'
      fullPath: '/answer/$questionId'
      preLoaderRoute: typeof AnswerQuestionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes/': {
      id: '/notes/'
      path: '/'
      fullPath: '/notes/'
      preLoaderRoute: typeof NotesIndexRouteImport
      parentRoute: typeof NotesRoute
    }
    '/notes/$noteId': {
      id: '/notes/$noteId'
      path: '/$noteId'
      fullPath: '/notes/$noteId'
      preLoaderRoute: typeof NotesNoteIdRouteImport
      parentRoute: typeof NotesRoute
    }
    '/plans/': {
      id: '/plans/'
      path: '/'
      fullPath: '/plans/'
      preLoaderRoute: typeof PlansIndexRouteImport
      parentRoute: typeof PlansRoute
    }
    '/plans/$planId': {
      id: '/plans/$planId'
      path: '/$planId'
      fullPath: '/plans/$planId'
      preLoaderRoute: typeof PlansPlanIdRouteImport
      parentRoute: typeof PlansRoute
    }
  }
}

interface NotesRouteChildren {
  NotesNoteIdRoute: typeof NotesNoteIdRoute
  NotesIndexRoute: typeof NotesIndexRoute
}

const NotesRouteChildren: NotesRouteChildren = {
  NotesNoteIdRoute: NotesNoteIdRoute,
  NotesIndexRoute: NotesIndexRoute,
}

const NotesRouteWithChildren = NotesRoute._addFileChildren(NotesRouteChildren)

interface PlansRouteChildren {
  PlansPlanIdRoute: typeof PlansPlanIdRoute
  PlansIndexRoute: typeof PlansIndexRoute
}

const PlansRouteChildren: PlansRouteChildren = {
  PlansPlanIdRoute: PlansPlanIdRoute,
  PlansIndexRoute: PlansIndexRoute,
}

const PlansRouteWithChildren = PlansRoute._addFileChildren(PlansRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalendarRoute: CalendarRoute,
  ConnectRoute: ConnectRoute,
  LocationRoute: LocationRoute,
  MediaRoute: MediaRoute,
  NotesRoute: NotesRouteWithChildren,
  NotificationsRoute: NotificationsRoute,
  PairingRoute: PairingRoute,
  PlansRoute: PlansRouteWithChildren,
  QuestionsRoute: QuestionsRoute,
  SettingsRoute: SettingsRoute,
  UpdatesRoute: UpdatesRoute,
  AnswerQuestionIdRoute: AnswerQuestionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
